/*
 * Lights Out — flip the whole grid off. Each tap toggles that cell and its four
 * orthogonal neighbours. Puzzles are generated by scrambling from solved, so
 * every board is guaranteed solvable. Fewest-moves best score saved.
 */
import { Engine } from '../engine.js';
import { Money } from '../monetization.js';
import { Meta } from '../meta.js';
import { gameOverDialog } from '../ui.js';

const N = 5;

export const LightsOut = {
  id: 'lights',
  name: 'Lights Out',
  tagline: 'Turn them all off. Each tap flips a cross.',
  type: 'dom',
  stat(store) { const b = store.get('lights_best', 0); return b ? 'Best: ' + b + ' moves' : 'Tap to play'; },

  mount(root) {
    const S = Engine.store;
    let grid, moves, over;
    root.innerHTML = `<div class="lo">
      <div class="lo-top">Moves <b id="lo-moves">0</b></div>
      <div id="lo-board" class="lo-board"></div>
      <button id="lo-new" class="m-new">New puzzle</button></div>`;
    const board = root.querySelector('#lo-board'); board.style.gridTemplateColumns = `repeat(${N}, 1fr)`;

    function flip(r, c, silent) {
      for (const [dr, dc] of [[0, 0], [0, 1], [0, -1], [1, 0], [-1, 0]]) { const rr = r + dr, cc = c + dc; if (rr >= 0 && rr < N && cc >= 0 && cc < N) grid[rr][cc] = !grid[rr][cc]; }
      if (!silent) { moves++; root.querySelector('#lo-moves').textContent = moves; }
    }
    const solved = () => grid.every(row => row.every(c => !c));
    function gen() {
      grid = Array.from({ length: N }, () => Array(N).fill(false));
      const k = 5 + Math.floor(Math.random() * 6);
      for (let i = 0; i < k; i++) flip(Math.floor(Math.random() * N), Math.floor(Math.random() * N), true);
      if (solved()) flip(0, 0, true);
      moves = 0; over = false; render();
    }
    function tap(r, c) { if (over) return; flip(r, c); Engine.sfx.tap(); Engine.haptic(8); render(); if (solved()) win(); }
    function render() {
      board.innerHTML = '';
      for (let r = 0; r < N; r++) for (let c = 0; c < N; c++) { const b = document.createElement('button'); b.className = 'lo-cell' + (grid[r][c] ? ' on' : ''); b.onclick = () => tap(r, c); board.appendChild(b); }
    }
    async function win() {
      over = true; Engine.sfx.good();
      const best = S.get('lights_best', 0); if (!best || moves < best) S.set('lights_best', moves);
      Meta.report('lights', { win: true, score: Math.max(0, 60 - moves) });
      const a = await gameOverDialog({ title: `Solved in ${moves} moves! 💡`, canRevive: false });
      if (a === 'again') { await Money.maybeInterstitial(); gen(); } else { await Money.maybeInterstitial(); root.dispatchEvent(new CustomEvent('exit-game', { bubbles: true })); }
    }
    root.querySelector('#lo-new').onclick = gen;
    gen();
    return { destroy() {} };
  },
};
