/*
 * Mahjong Solitaire — match pairs of identical FREE tiles to clear the board.
 * A tile is free when nothing covers it and one side (left/right) is open.
 * Boards are generated by reverse "peeling" — removing free pairs from a full
 * pyramid — which guarantees every deal is solvable.
 */
import { Engine } from '../engine.js';
import { Money } from '../monetization.js';
import { Meta } from '../meta.js';
import { gameOverDialog, toast } from '../ui.js';

const LAYERS = [{ cols: 6, rows: 6 }, { cols: 4, rows: 4 }, { cols: 2, rows: 2 }];
const BASE = 6;
const SYMS = ['🀄', '🎋', '🌸', '🐉', '⭐', '🍀', '🔔', '💎', '🍑', '🎐', '🏮', '🪷', '🐲', '🎍'];
const id = (s) => `${s.layer},${s.gx},${s.gy}`;

function buildSlots() {
  const slots = [];
  LAYERS.forEach((L, layer) => { const ox = (BASE - L.cols) / 2, oy = (BASE - L.rows) / 2; for (let r = 0; r < L.rows; r++) for (let c = 0; c < L.cols; c++) slots.push({ layer, gx: ox + c, gy: oy + r }); });
  return slots;
}
const isFree = (s, occ) => !occ.has(`${s.layer + 1},${s.gx},${s.gy}`) && (!occ.has(`${s.layer},${s.gx - 1},${s.gy}`) || !occ.has(`${s.layer},${s.gx + 1},${s.gy}`));

function generate() {
  const slots = buildSlots();
  for (let attempt = 0; attempt < 50; attempt++) {
    const occ = new Set(slots.map(id)); const sym = {}; const order = []; let pair = 0; let ok = true;
    while (occ.size) {
      const free = slots.filter(s => occ.has(id(s)) && isFree(s, occ));
      if (free.length < 2) { ok = false; break; }
      for (let i = free.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [free[i], free[j]] = [free[j], free[i]]; }
      const a = free[0], b = free[1], symbol = SYMS[pair++ % SYMS.length];
      sym[id(a)] = symbol; sym[id(b)] = symbol; occ.delete(id(a)); occ.delete(id(b)); order.push([id(a), id(b)]);
    }
    if (ok) return { slots, sym, order };
  }
  return null;
}

export const Mahjong = {
  id: 'mahjong',
  name: 'Mahjong',
  tagline: 'Match free tiles, clear the board.',
  type: 'dom',
  stat(store) { return 'Solved: ' + store.get('mj_solved', 0); },

  mount(root) {
    const S = Engine.store;
    let slots, sym, occ, sel, over;
    root.innerHTML = `<div class="mj">
      <div class="mj-bar"><span id="mj-left"></span><button id="mj-shuffle" class="ms-flag">🔀 Shuffle</button><button id="mj-new" class="m-new">New</button></div>
      <div id="mj-board" class="mj-board"></div></div>`;
    const boardEl = root.querySelector('#mj-board');

    function deal() { const g = generate(); slots = g.slots; sym = { ...g.sym }; occ = new Set(slots.map(id)); sel = null; over = false; render(); }
    function freePairsExist() {
      const free = slots.filter(s => occ.has(id(s)) && isFree(s, occ));
      const seen = {}; for (const s of free) { const v = sym[id(s)]; if (seen[v]) return true; seen[v] = 1; } return false;
    }
    function shuffle() {
      const rem = slots.filter(s => occ.has(id(s))); const vals = rem.map(s => sym[id(s)]);
      for (let i = vals.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [vals[i], vals[j]] = [vals[j], vals[i]]; }
      rem.forEach((s, i) => sym[id(s)] = vals[i]); sel = null; toast('Shuffled'); render();
    }
    function tap(s) {
      if (over || !occ.has(id(s)) || !isFree(s, occ)) { Engine.sfx.bad(); return; }
      const k = id(s);
      if (sel === k) { sel = null; render(); return; }
      if (sel && sym[sel] === sym[k]) {
        occ.delete(sel); occ.delete(k); sel = null; Engine.sfx.good(); Engine.haptic(12); render();
        if (occ.size === 0) return win();
        if (!freePairsExist()) toast('No moves — shuffle!');
      } else { sel = k; Engine.sfx.tap(); render(); }
    }
    function render() {
      root.querySelector('#mj-left').textContent = `${occ.size} tiles`;
      boardEl.innerHTML = '';
      const tw = 34, th = 44, off = 6;
      const sorted = slots.filter(s => occ.has(id(s))).sort((a, b) => a.layer - b.layer || a.gy - b.gy || a.gx - b.gx);
      let maxX = 0, maxY = 0;
      for (const s of sorted) {
        const free = isFree(s, occ);
        const el = document.createElement('button');
        el.className = 'mj-tile' + (free ? '' : ' locked') + (sel === id(s) ? ' sel' : '');
        const x = s.gx * tw + s.layer * off, y = s.gy * th - s.layer * off;
        el.style.left = x + 'px'; el.style.top = y + 'px'; el.style.zIndex = s.layer * 50 + s.gy + 10;
        el.textContent = sym[id(s)]; el.onclick = () => tap(s);
        boardEl.appendChild(el); maxX = Math.max(maxX, x + tw); maxY = Math.max(maxY, y + th);
      }
      boardEl.style.width = maxX + 'px'; boardEl.style.height = maxY + 'px';
    }
    async function win() {
      over = true; S.set('mj_solved', S.get('mj_solved', 0) + 1); Engine.sfx.good();
      Meta.report('mahjong', { win: true, score: 50 });
      const a = await gameOverDialog({ title: 'Board cleared! 🀄', canRevive: false });
      if (a === 'again') { await Money.maybeInterstitial(); deal(); } else { await Money.maybeInterstitial(); root.dispatchEvent(new CustomEvent('exit-game', { bubbles: true })); }
    }
    root.querySelector('#mj-shuffle').onclick = shuffle;
    root.querySelector('#mj-new').onclick = deal;
    deal();
    return { destroy() {} };
  },
};
export const _test = { generate, isFree, id, buildSlots };
